//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagneziaComplex.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFavouriteTrainers
    {
        public int idClientFavoriteTrainers { get; set; }
        public int idClient { get; set; }
        public int idEmployee { get; set; }
        public int CountTrainings { get; set; }
        public System.DateTime DateSale { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
