//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagneziaComplex.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTraining
    {
        public int idClientTraining { get; set; }
        public int idClient { get; set; }
        public int idTraining { get; set; }
        public System.DateTime DateSale { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Training Training { get; set; }
    }
}
