//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagneziaComplex.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionClient
    {
        public int idSubscriptionClient { get; set; }
        public int idClient { get; set; }
        public int idSubscription { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool IsActive { get; set; }
        public int idClub { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Club Club { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
